name: ci
on:
  push:
    branches:
      - master
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install weasyprint==62.3
      - run: pip install pydyf==0.10.0
      - run: pip install mkdocs
      - run: pip install mkdocs-carbon
      - run: pip install mkdocs-get-deps
      - run: pip install mkdocs-material
      - run: pip install mkdocs-with-pdf
      - run: pip install mkdocs-material-extensions
      - run: pip install mkdocs-minify-plugin
      - run: pip install mkdocs-git-revision-date-localized-plugin
      - run: pip install mkdocs-extra-sass-plugin
      - run: pip install livereload
      - run: pip install qrcode
      - run: mkdocs build
      - run: mkdocs gh-deploy --force
